CREATE DATABASE IoT;

USE IoT;

-- TABLA DE LECTOR DE TEMPERATURA Y HUMEDAD | ALONSO
CREATE TABLE log_temp (
	log_id INT PRIMARY KEY AUTO_INCREMENT,
	log_date TIMESTAMP NOT NULL,
	temp FLOAT NOT NULL,
	humidity FLOAT NOT NULL
);

-- TABLA DE LECTOR DE VOLUMEN | ALE
CREATE TABLE log_volume (
	log_id INT PRIMARY KEY AUTO_INCREMENT,
	log_date TIMESTAMP NOT NULL,
	decibels INT NOT NULL
);

-- TABALA DE RFID | DEBANHI
CREATE TABLE log_uid(
	log_id INT PRIMARY KEY AUTO_INCREMENT,
	log_date TIMESTAMP NOT NULL,
	uid BIGINT NOT NULL
);

CREATE TABLE accepted_uid (
	log_id INT PRIMARY KEY AUTO_INCREMENT,
	uid BIGINT NOT NULL
);

-- TABLA DE PRESION | DAVID
CREATE TABLE log_pressure(
	log_id INT PRIMARY KEY AUTO_INCREMENT,
	log_date TIMESTAMP NOT NULL,
    pressure INT NOT NULL
);

